pipeline:
  build:
    image: emscripten/emsdk
    commands:
      - cd build
      - bash -c "emcmake cmake -G 'Unix Makefiles' .. "
      - bash -c "emmake make"
  

  deploy:
    image: appleboy/drone-scp
    host: frank-wolbring.de
    username: 
      from_secret: ssh_user
    key:
      from_secret: ssk_key
    target: ~/test/
    source: public/*