kind: pipeline
type: docker
name: Build

steps:
  - name: build
    image: emscripten/emsdk
    commands:
      - cd build
      - bash -c "emcmake cmake -G 'Unix Makefiles' .. "
      - bash -c "emmake make"
  - name: deploy
    image: appleboy/drone-scp
    settings:
      strip_components: 1
      source: public/*
      host:
        from_secret: deploy_host
      username:
        from_secret: ssh_user
      key:
        from_secret: ssh_key
      target:
        from_secret: deploy_path
trigger:
  branch:
    - gametest

---
kind: pipeline
type: docker
name: Notify
clone:
  disable: true
steps:
  - name: notify
    image: appleboy/drone-discord
    settings:
      webhook_id:
        from_secret: webhook_id
      webhook_token:
        from_secret: webhook_token
      message: >
        {{#success build.status}}
          Build {{build.number}} ready for testing.
          http://gametest.frank-wolbring.de/
        {{else}}
          build {{build.number}} failed.
        {{/success}}

depends_on:
  - Build
trigger:
  branch:
    - gametest
  status:
      - failure
      - success