pipeline:
  build:
    image: emscripten/emsdk
    commands:
      - cd build
      - bash -c "emcmake cmake -G 'Unix Makefiles' .. "
      - bash -c "emmake make"

  deploy:
    image: appleboy/drone-scp
    strip_components: 1
    source: public/*
    host:
      from_secret: deploy_host
    username:
      from_secret: ssh_user
    key:
      from_secret: ssh_key
    target:
      from_secret: deploy_path
