kind: pipeline
type: docker
name: default

steps:
- name: build
  image: emscripten/emsdk
  commands:
  - cd build
  - bash -c "emcmake cmake -G 'Unix Makefiles' .. "
  - bash -c "emmake make"
- name: deploy
  image: appleboy/drone-scp
  settings:
    strip_components: 1
    source: public/*
    host:
      from_secret: deploy_host
    username:
      from_secret: ssh_user
    key:
      from_secret: ssh_key
    target:
      from_secret: deploy_path

trigger:
  branch:
  - gametest