pipeline:
  build:
    image: emscripten/emsdk
    commands:
      - cd build
      - bash -c "emcmake cmake -G 'Unix Makefiles' .. "
      - bash -c "emmake make"

  deploy:
    image: appleboy/drone-scp
    host: 
      from_secret: deploy_host
    username:
      from_secret: ssh_user
    key:
      from_secret: ssh_key
    strip_components: 1
    target: 
      from_secret: deploy_path
    source: public/*
